-- Project 318 foundational public schema.
-- Reconstructed from reviewed schema-only production exports. No row data is included.
-- Run before every other Project 318 forward migration.
begin;

create table if not exists public.leads (
  id bigint generated always as identity primary key,
  created_at timestamptz default now(),
  name text,
  company text,
  email text,
  phone text,
  event_date date,
  guests integer,
  menu text,
  event_type text,
  budget numeric,
  notes text,
  status text default 'New'
);

create table if not exists public.website_content (
  id bigint generated by default as identity primary key,
  page text not null,
  content_key text not null,
  content_value text not null default '',
  updated_at timestamptz not null default now(),
  constraint website_content_page_content_key_key unique (page, content_key)
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  slug text not null,
  name text not null,
  subtitle text default '',
  price text default '',
  button_text text default '',
  button_link text default '',
  image_file text default '',
  is_active boolean default true,
  sort_order integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint menu_items_slug_key unique (slug)
);

alter table public.leads enable row level security;
alter table public.website_content enable row level security;
alter table public.menu_items enable row level security;

drop policy if exists "Anyone can insert leads" on public.leads;
create policy "Anyone can insert leads"
on public.leads for insert to anon
with check (true);

drop policy if exists "Authenticated users can view leads" on public.leads;
create policy "Authenticated users can view leads"
on public.leads for select to authenticated
using (true);

drop policy if exists "Public can read website content" on public.website_content;
create policy "Public can read website content"
on public.website_content for select to anon, authenticated
using (true);

drop policy if exists "Authenticated users can add website content" on public.website_content;
create policy "Authenticated users can add website content"
on public.website_content for insert to authenticated
with check (true);

drop policy if exists "Authenticated users can update website content" on public.website_content;
create policy "Authenticated users can update website content"
on public.website_content for update to authenticated
using (true) with check (true);

drop policy if exists "Authenticated users can delete website content" on public.website_content;
create policy "Authenticated users can delete website content"
on public.website_content for delete to authenticated
using (true);

drop policy if exists "Public can read menu items" on public.menu_items;
create policy "Public can read menu items"
on public.menu_items for select to anon, authenticated
using (is_active = true);

drop policy if exists "Authenticated users can manage menu items" on public.menu_items;
create policy "Authenticated users can manage menu items"
on public.menu_items for all to authenticated
using (true) with check (true);

revoke all on public.leads, public.website_content, public.menu_items from anon, authenticated, service_role;
grant select, insert, references on public.leads to anon;
grant select, insert, update, references on public.leads to authenticated;
grant all on public.leads to service_role;
grant select, insert, update, references on public.website_content, public.menu_items to anon;
grant select, insert, update, delete, references on public.website_content, public.menu_items to authenticated;
grant all on public.website_content, public.menu_items to service_role;

grant usage on sequence public.leads_id_seq to anon, authenticated, service_role;
grant usage on sequence public.website_content_id_seq, public.menu_items_id_seq to anon, authenticated, service_role;

comment on table public.leads is 'Public catering quote requests; CRM columns are added by later migrations.';
comment on table public.website_content is 'Editable public website copy keyed by page and content key.';
comment on table public.menu_items is 'Editable catering menu packages displayed on the public website.';

commit;
