-- Project 318 Booking Calendar
-- Run manually in Supabase Dashboard > SQL Editor after reviewing this migration.
-- This migration is non-destructive and safe to run more than once.

begin;

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  customer_name text not null check (length(btrim(customer_name)) > 0),
  company_name text not null default '',
  email text not null default '',
  phone text not null default '',

  event_title text not null check (length(btrim(event_title)) > 0),
  event_type text not null check (length(btrim(event_type)) > 0),
  event_date date not null,
  start_time time not null,
  end_time time not null,
  guest_count integer check (guest_count is null or guest_count >= 0),
  venue_name text not null default '',
  venue_address text not null default '',

  quote_id bigint references public.leads(id) on delete set null,
  quote_amount numeric(12, 2) check (quote_amount is null or quote_amount >= 0),

  status text not null default 'Pending'
    check (status in ('Pending', 'Confirmed', 'Completed', 'Cancelled')),
  internal_notes text not null default '',

  constraint bookings_end_after_start check (end_time > start_time)
);

create unique index if not exists bookings_quote_id_unique
  on public.bookings (quote_id)
  where quote_id is not null;

create index if not exists bookings_event_date_idx
  on public.bookings (event_date);

create index if not exists bookings_status_idx
  on public.bookings (status);

create index if not exists bookings_event_type_idx
  on public.bookings (event_type);

create index if not exists bookings_customer_name_idx
  on public.bookings (lower(customer_name));

create or replace function public.set_bookings_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists bookings_set_updated_at on public.bookings;
create trigger bookings_set_updated_at
before update on public.bookings
for each row
execute function public.set_bookings_updated_at();

alter table public.bookings enable row level security;

drop policy if exists "Authenticated administrators can read bookings" on public.bookings;
create policy "Authenticated administrators can read bookings"
on public.bookings
for select
to authenticated
using (true);

drop policy if exists "Authenticated administrators can create bookings" on public.bookings;
create policy "Authenticated administrators can create bookings"
on public.bookings
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated administrators can update bookings" on public.bookings;
create policy "Authenticated administrators can update bookings"
on public.bookings
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated administrators can delete bookings" on public.bookings;
create policy "Authenticated administrators can delete bookings"
on public.bookings
for delete
to authenticated
using (true);

revoke all on table public.bookings from anon;
grant select, insert, update, delete on table public.bookings to authenticated;
grant usage, select on sequence public.bookings_id_seq to authenticated;

comment on table public.bookings is
  'Private catering bookings managed by authenticated Project 318 administrators.';

comment on column public.bookings.quote_id is
  'Optional relationship to the originating public.leads quote request.';

commit;
