-- Project 318 administrator-managed marketing spend and ROAS reporting.
-- Apply after marketing-attribution.sql and marketing-funnel-reporting.sql.
begin;

create table if not exists public.marketing_spend (
  id bigint generated by default as identity primary key,
  spend_date date not null,
  source text not null,
  medium text not null default '',
  campaign text not null default '',
  amount numeric(12,2) not null check (amount >= 0),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint marketing_spend_source_length check (length(source) between 1 and 255),
  constraint marketing_spend_medium_length check (length(medium) <= 255),
  constraint marketing_spend_campaign_length check (length(campaign) <= 500),
  constraint marketing_spend_notes_length check (length(notes) <= 1000)
);

create index if not exists marketing_spend_date_source_idx
  on public.marketing_spend(spend_date desc, source, campaign);

alter table public.marketing_spend enable row level security;

drop policy if exists "Marketing administrators can manage spend" on public.marketing_spend;
create policy "Marketing administrators can manage spend" on public.marketing_spend
for all to authenticated using (public.crm_is_admin()) with check (public.crm_is_admin());

revoke all on public.marketing_spend from anon, authenticated;
grant select, insert, update, delete on public.marketing_spend to authenticated;
grant usage, select on sequence public.marketing_spend_id_seq to authenticated;

create or replace function public.marketing_spend_summary(
  p_start date,
  p_end date,
  p_model text default 'last_non_direct'
)
returns table (
  source text,
  medium text,
  campaign text,
  spend numeric,
  revenue numeric,
  quote_count bigint,
  booked_count bigint,
  cost_per_quote numeric,
  cost_per_booking numeric,
  roas numeric
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.crm_is_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  if p_model not in ('first', 'last_non_direct') then
    raise exception 'Unsupported attribution model';
  end if;
  if p_start is null or p_end is null or p_end < p_start then
    raise exception 'Invalid reporting date range';
  end if;

  return query
  with spend as (
    select lower(btrim(ms.source)) as source_key,
      lower(btrim(ms.medium)) as medium_key,
      lower(btrim(ms.campaign)) as campaign_key,
      sum(ms.amount)::numeric as spend
    from public.marketing_spend ms
    where ms.spend_date between p_start and p_end
    group by 1,2,3
  ), revenue as (
    select lower(btrim(r.source)) as source_key,
      lower(btrim(r.medium)) as medium_key,
      lower(btrim(r.campaign)) as campaign_key,
      sum(r.revenue)::numeric as revenue
    from public.marketing_revenue_attribution(p_start,p_end,p_model) r
    group by 1,2,3
  ), funnel as (
    select lower(btrim(f.source)) as source_key,
      lower(btrim(f.medium)) as medium_key,
      lower(btrim(f.campaign)) as campaign_key,
      sum(f.quote_count)::bigint as quote_count,
      sum(f.booked_count)::bigint as booked_count
    from public.marketing_quote_funnel(p_start,p_end,p_model) f
    group by 1,2,3
  ), keys as (
    select source_key,medium_key,campaign_key from spend
    union select source_key,medium_key,campaign_key from revenue
    union select source_key,medium_key,campaign_key from funnel
  )
  select
    coalesce(nullif(k.source_key,''),'unattributed')::text,
    coalesce(nullif(k.medium_key,''),'(none)')::text,
    coalesce(k.campaign_key,'')::text,
    coalesce(s.spend,0)::numeric,
    coalesce(r.revenue,0)::numeric,
    coalesce(f.quote_count,0)::bigint,
    coalesce(f.booked_count,0)::bigint,
    case when coalesce(f.quote_count,0)>0 then round(coalesce(s.spend,0)/f.quote_count,2) else null end,
    case when coalesce(f.booked_count,0)>0 then round(coalesce(s.spend,0)/f.booked_count,2) else null end,
    case when coalesce(s.spend,0)>0 then round(coalesce(r.revenue,0)/s.spend,2) else null end
  from keys k
  left join spend s using(source_key,medium_key,campaign_key)
  left join revenue r using(source_key,medium_key,campaign_key)
  left join funnel f using(source_key,medium_key,campaign_key)
  order by coalesce(r.revenue,0) desc, coalesce(s.spend,0) desc;
end;
$$;

revoke all on function public.marketing_spend_summary(date,date,text) from public, anon;
grant execute on function public.marketing_spend_summary(date,date,text) to authenticated;

comment on table public.marketing_spend is 'Administrator-entered advertising and marketing costs used for ROAS reporting.';

commit;
