-- Project 318 Release 1: secure lead intake, consent evidence, and email state.
-- Apply after marketing-attribution.sql. This migration is additive and rerunnable.
begin;

create extension if not exists pgcrypto;

alter table public.leads add column if not exists submission_source text not null default 'legacy';
alter table public.leads add column if not exists customer_confirmation_status text not null default 'not_attempted';
alter table public.leads add column if not exists owner_notification_status text not null default 'not_attempted';
alter table public.leads add column if not exists last_email_attempt_at timestamptz;
alter table public.leads add column if not exists marketing_consent_status text not null default 'unknown';
alter table public.leads add column if not exists deduplicated boolean not null default false;
alter table public.leads add column if not exists abuse_review_required boolean not null default false;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'leads_submission_source_check'
      and conrelid = 'public.leads'::regclass
  ) then
    alter table public.leads add constraint leads_submission_source_check
      check (submission_source in ('legacy', 'guided_quote', 'contact_form', 'admin'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'leads_customer_confirmation_status_check'
      and conrelid = 'public.leads'::regclass
  ) then
    alter table public.leads add constraint leads_customer_confirmation_status_check
      check (customer_confirmation_status in ('not_attempted', 'accepted', 'failed', 'manual_setup'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'leads_owner_notification_status_check'
      and conrelid = 'public.leads'::regclass
  ) then
    alter table public.leads add constraint leads_owner_notification_status_check
      check (owner_notification_status in ('not_attempted', 'accepted', 'failed', 'manual_setup'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'leads_marketing_consent_status_check'
      and conrelid = 'public.leads'::regclass
  ) then
    alter table public.leads add constraint leads_marketing_consent_status_check
      check (marketing_consent_status in ('unknown', 'granted', 'declined', 'withdrawn'));
  end if;
end;
$$;

create table if not exists public.lead_submission_idempotency (
  idempotency_key uuid primary key,
  request_hash text not null,
  lead_id bigint references public.leads(id) on delete restrict,
  submission_source text not null,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint lead_submission_idempotency_hash_length check (length(request_hash) between 32 and 128),
  constraint lead_submission_idempotency_source_check check (submission_source in ('guided_quote', 'contact_form'))
);

create table if not exists public.lead_rate_limit_events (
  id bigint generated by default as identity primary key,
  rate_limit_key text not null,
  created_at timestamptz not null default now(),
  constraint lead_rate_limit_key_length check (length(rate_limit_key) between 32 and 128)
);

create index if not exists lead_rate_limit_events_key_created_idx
  on public.lead_rate_limit_events(rate_limit_key, created_at desc);

create table if not exists public.marketing_consent_history (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete restrict,
  lead_id bigint not null references public.leads(id) on delete restrict,
  channel text not null default 'email',
  granted boolean not null,
  disclosure_version text not null,
  disclosure_id text not null,
  disclosure_text text not null,
  submission_source text not null,
  recorded_at timestamptz not null default now(),
  withdrawn_at timestamptz,
  constraint marketing_consent_channel_check check (channel in ('email', 'sms')),
  constraint marketing_consent_disclosure_version_length check (length(disclosure_version) between 1 and 100),
  constraint marketing_consent_disclosure_id_length check (length(disclosure_id) between 1 and 200),
  constraint marketing_consent_disclosure_text_length check (length(disclosure_text) between 1 and 2000),
  constraint marketing_consent_source_check check (submission_source in ('guided_quote', 'contact_form', 'admin')),
  constraint marketing_consent_withdrawal_check check (withdrawn_at is null or withdrawn_at >= recorded_at)
);

create index if not exists marketing_consent_history_customer_recorded_idx
  on public.marketing_consent_history(customer_id, recorded_at desc);
create index if not exists marketing_consent_history_lead_recorded_idx
  on public.marketing_consent_history(lead_id, recorded_at desc);

create table if not exists public.lead_email_deliveries (
  id uuid primary key default gen_random_uuid(),
  lead_id bigint not null references public.leads(id) on delete restrict,
  message_type text not null,
  status text not null,
  provider text not null default '',
  provider_reference text not null default '',
  failure_code text not null default '',
  attempted_at timestamptz not null default now(),
  accepted_at timestamptz,
  retry_state text not null default 'not_scheduled',
  constraint lead_email_message_type_check check (message_type in ('owner_notification', 'customer_confirmation')),
  constraint lead_email_status_check check (status in ('accepted', 'failed', 'manual_setup')),
  constraint lead_email_retry_state_check check (retry_state in ('not_scheduled', 'retry_available', 'resolved')),
  constraint lead_email_provider_length check (length(provider) <= 100),
  constraint lead_email_provider_reference_length check (length(provider_reference) <= 500),
  constraint lead_email_failure_code_length check (length(failure_code) <= 200),
  constraint lead_email_accepted_check check (
    (status = 'accepted' and accepted_at is not null)
    or (status <> 'accepted' and accepted_at is null)
  )
);

create index if not exists lead_email_deliveries_lead_attempted_idx
  on public.lead_email_deliveries(lead_id, attempted_at desc);

alter table public.lead_submission_idempotency enable row level security;
alter table public.lead_rate_limit_events enable row level security;
alter table public.marketing_consent_history enable row level security;
alter table public.lead_email_deliveries enable row level security;

drop policy if exists "CRM administrators can read submission receipts" on public.lead_submission_idempotency;
create policy "CRM administrators can read submission receipts"
on public.lead_submission_idempotency for select to authenticated
using (public.crm_is_admin());

drop policy if exists "CRM administrators can read consent history" on public.marketing_consent_history;
create policy "CRM administrators can read consent history"
on public.marketing_consent_history for select to authenticated
using (public.crm_is_admin());

drop policy if exists "CRM administrators can read email deliveries" on public.lead_email_deliveries;
create policy "CRM administrators can read email deliveries"
on public.lead_email_deliveries for select to authenticated
using (public.crm_is_admin());

revoke all on public.lead_submission_idempotency, public.lead_rate_limit_events,
  public.marketing_consent_history, public.lead_email_deliveries from public, anon, authenticated;
grant select on public.lead_submission_idempotency, public.marketing_consent_history,
  public.lead_email_deliveries to authenticated;
grant all on public.lead_submission_idempotency, public.lead_rate_limit_events,
  public.marketing_consent_history, public.lead_email_deliveries to service_role;
grant usage, select on sequence public.lead_rate_limit_events_id_seq to service_role;

create or replace function public.submit_release1_lead(
  p_idempotency_key uuid,
  p_request_hash text,
  p_rate_limit_key text,
  p_rate_limit_max integer,
  p_rate_limit_window_seconds integer,
  p_submission_source text,
  p_name text,
  p_company text,
  p_email text,
  p_phone text,
  p_event_date date,
  p_guests integer,
  p_menu text,
  p_event_type text,
  p_budget numeric,
  p_notes text,
  p_attribution jsonb,
  p_marketing_consent boolean,
  p_disclosure_version text,
  p_disclosure_id text,
  p_disclosure_text text
)
returns table (lead_id bigint, deduplicated boolean)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_existing public.lead_submission_idempotency%rowtype;
  v_lead_id bigint;
  v_customer_id uuid;
  v_count integer;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Server authorization required' using errcode = '42501';
  end if;
  if p_submission_source not in ('guided_quote', 'contact_form') then
    raise exception 'Invalid submission source' using errcode = '22023';
  end if;
  if p_idempotency_key is null
     or length(btrim(coalesce(p_request_hash, ''))) < 32
     or length(btrim(coalesce(p_rate_limit_key, ''))) < 32 then
    raise exception 'Submission security values are invalid' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key::text, 0));

  select * into v_existing
  from public.lead_submission_idempotency
  where idempotency_key = p_idempotency_key
  for update;

  if found then
    if v_existing.request_hash <> p_request_hash then
      raise exception 'Idempotency key was already used for another request' using errcode = '23505';
    end if;
    if v_existing.lead_id is null then
      raise exception 'Submission is still processing' using errcode = '40001';
    end if;
    update public.leads set deduplicated = true where id = v_existing.lead_id;
    return query select v_existing.lead_id, true;
    return;
  end if;

  insert into public.lead_submission_idempotency(
    idempotency_key, request_hash, submission_source
  ) values (p_idempotency_key, p_request_hash, p_submission_source);

  perform pg_advisory_xact_lock(hashtextextended(p_rate_limit_key, 1));

  select count(*) into v_count
  from public.lead_rate_limit_events
  where rate_limit_key = p_rate_limit_key
    and created_at >= now() - make_interval(secs => greatest(p_rate_limit_window_seconds, 60));

  if v_count >= least(greatest(p_rate_limit_max, 1), 100) then
    raise exception 'Submission rate limit exceeded' using errcode = 'P0001';
  end if;

  insert into public.lead_rate_limit_events(rate_limit_key) values (p_rate_limit_key);

  v_lead_id := public.submit_quote_with_attribution(
    p_name, p_company, p_email, p_phone, p_event_date, p_guests,
    p_menu, p_event_type, p_budget, p_notes, coalesce(p_attribution, '{}'::jsonb)
  );

  update public.leads
  set submission_source = p_submission_source,
      marketing_consent_status = case when p_marketing_consent then 'granted' else 'declined' end
  where id = v_lead_id
  returning customer_id into v_customer_id;

  insert into public.marketing_consent_history(
    customer_id, lead_id, channel, granted, disclosure_version,
    disclosure_id, disclosure_text, submission_source
  ) values (
    v_customer_id, v_lead_id, 'email', p_marketing_consent,
    p_disclosure_version, p_disclosure_id, p_disclosure_text, p_submission_source
  );

  update public.lead_submission_idempotency
  set lead_id = v_lead_id, completed_at = now()
  where idempotency_key = p_idempotency_key;

  return query select v_lead_id, false;
end;
$$;

revoke all on function public.submit_release1_lead(
  uuid,text,text,integer,integer,text,text,text,text,text,date,integer,text,text,numeric,text,jsonb,boolean,text,text,text
) from public, anon, authenticated;
grant execute on function public.submit_release1_lead(
  uuid,text,text,integer,integer,text,text,text,text,text,date,integer,text,text,numeric,text,jsonb,boolean,text,text,text
) to service_role;

create or replace function public.record_lead_email_delivery(
  p_lead_id bigint,
  p_message_type text,
  p_status text,
  p_provider text,
  p_provider_reference text,
  p_failure_code text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.role() <> 'service_role' then
    raise exception 'Server authorization required' using errcode = '42501';
  end if;
  if p_message_type not in ('owner_notification', 'customer_confirmation')
     or p_status not in ('accepted', 'failed', 'manual_setup') then
    raise exception 'Invalid email delivery state' using errcode = '22023';
  end if;

  insert into public.lead_email_deliveries(
    lead_id, message_type, status, provider, provider_reference,
    failure_code, accepted_at, retry_state
  ) values (
    p_lead_id, p_message_type, p_status,
    left(btrim(coalesce(p_provider, '')), 100),
    left(btrim(coalesce(p_provider_reference, '')), 500),
    left(btrim(coalesce(p_failure_code, '')), 200),
    case when p_status = 'accepted' then now() else null end,
    case when p_status = 'failed' then 'retry_available' else 'not_scheduled' end
  );

  update public.leads
  set customer_confirmation_status = case
        when p_message_type = 'customer_confirmation' then p_status
        else customer_confirmation_status end,
      owner_notification_status = case
        when p_message_type = 'owner_notification' then p_status
        else owner_notification_status end,
      last_email_attempt_at = now()
  where id = p_lead_id;
end;
$$;

revoke all on function public.record_lead_email_delivery(bigint,text,text,text,text,text)
  from public, anon, authenticated;
grant execute on function public.record_lead_email_delivery(bigint,text,text,text,text,text)
  to service_role;

comment on table public.marketing_consent_history is
  'Append-only evidence of explicit marketing consent decisions. Transactional email does not depend on this consent.';
comment on table public.lead_email_deliveries is
  'Private delivery-attempt ledger. Provider secrets and payloads are never stored.';

commit;
