(function () {
  "use strict";
  const loading=document.getElementById("portalLoading"),errorBox=document.getElementById("portalError"),app=document.getElementById("portalApp"),content=document.getElementById("portalContent");
  const token=new URLSearchParams(location.hash.slice(1)).get("token")||"";
  let data=null,view="proposals";
  const esc=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
  const money=(v)=>Number(v||0).toLocaleString("en-US",{style:"currency",currency:"USD"});
  async function snapshot(){const r=await window.supabaseClient.rpc("sales_portal_snapshot",{p_token:token});if(r.error)throw r.error;return r.data;}
  async function respond(proposalId,action,message=""){const r=await window.supabaseClient.rpc("sales_portal_respond",{p_token:token,p_proposal_id:proposalId||null,p_action:action,p_message:message});if(r.error)throw r.error;data=await snapshot();render();}
  function proposals(){return `<div class="portal-grid">${(data.proposals||[]).map(p=>`<article class="portal-card"><p class="kicker">${esc(p.status)}</p><h2>${esc(p.title)}</h2><p>${esc(p.version?.introduction||"")}</p>${(p.version?.items||[]).map(i=>`<p>${esc(i.description)} · ${i.quantity} × ${money(i.unit_price)}</p>`).join("")}<p class="portal-money">${money(p.version?.total_amount)}</p><p class="portal-meta">Expires ${esc(p.expiration_date||"when confirmed")}</p><div class="portal-actions">${["sent","viewed"].includes(p.status)?`<button class="approve" data-proposal-action="approve" data-id="${p.id}">Approve</button><button class="decline" data-proposal-action="decline" data-id="${p.id}">Decline</button>`:""}<button data-proposal-pdf="${p.id}">Download PDF</button><button data-question="${p.id}">Ask a Question</button></div></article>`).join("")||'<article class="portal-card"><h2>No active proposals</h2><p>Your proposals will appear here when they are ready.</p></article>'}</div>`;}
  function events(){return `<div class="portal-grid">${(data.bookings||[]).map(b=>`<article class="portal-card"><h2>${esc(b.event_title)}</h2><p>${esc(b.event_date)} · ${esc(b.start_time)}</p><p class="portal-meta">${esc(b.venue_name)}<br>${esc(b.venue_address)}</p><strong>${esc(b.status)}</strong></article>`).join("")||'<article class="portal-card">No events scheduled.</article>'}</div>`;}
  function invoices(){return `<div class="portal-grid">${(data.invoices||[]).map(i=>`<article class="portal-card"><h2>${esc(i.invoice_number||"Invoice")}</h2><p class="portal-money">${money(i.balance_due)} due</p><p>Total ${money(i.total_amount)} · Paid ${money(i.paid_amount)}</p><p class="portal-meta">Due ${esc(i.due_date||"—")}</p></article>`).join("")||'<article class="portal-card">No issued invoices.</article>'}</div><h2>Payment history</h2><div>${(data.payments||[]).map(p=>`<p class="portal-message">${esc(p.payment_date)} · ${money(p.amount)} · ${esc(p.payment_method)}</p>`).join("")||"<p>No payments recorded.</p>"}</div>`;}
  function documents(){return `<div class="portal-grid"><section class="portal-card"><h2>Upload a document</h2><p>PDF, JPG, PNG, or WebP · maximum 4 MB.</p><form id="portalDocumentForm"><input id="portalDocumentFile" type="file" accept=".pdf,image/jpeg,image/png,image/webp" required><div class="portal-actions"><button type="submit">Upload Securely</button></div><p id="portalDocumentStatus" role="status"></p></form></section><section class="portal-card"><h2>Your documents</h2>${(data.documents||[]).map(d=>`<p class="portal-message">${esc(d.file_name)}<br><small>${esc(d.mime_type)}</small></p>`).join("")||"<p>No documents uploaded.</p>"}</section></div>`;}
  function messages(){return `<div class="portal-grid"><section class="portal-card"><h2>Send a question</h2><form id="portalMessageForm" class="portal-message-form"><textarea id="portalMessage" required maxlength="5000" placeholder="How can we help?"></textarea><div class="portal-actions"><button type="submit">Send Question</button></div><p id="portalMessageStatus" role="status"></p></form></section><section><h2>Conversation</h2>${(data.messages||[]).map(m=>`<div class="portal-message"><strong>${m.direction==="customer"?"You":"318 Food Co."}</strong><p>${esc(m.body)}</p></div>`).join("")||"<p>No messages yet.</p>"}</section></div>`;}
  function render(){document.querySelectorAll("[data-portal-view]").forEach(b=>b.classList.toggle("active",b.dataset.portalView===view));content.innerHTML=({proposals,events,invoices,documents,messages}[view])();content.querySelectorAll("[data-proposal-action]").forEach(b=>b.onclick=()=>{if(confirm(`${b.dataset.proposalAction} this proposal?`))respond(b.dataset.id,b.dataset.proposalAction).catch(showError);});content.querySelectorAll("[data-proposal-pdf]").forEach(b=>b.onclick=async()=>{try{const response=await fetch(`/api/proposal-pdf?id=${encodeURIComponent(b.dataset.proposalPdf)}`,{headers:{"X-Portal-Token":token}});if(!response.ok)throw new Error((await response.json()).error);const url=URL.createObjectURL(await response.blob()),a=document.createElement("a");a.href=url;a.download="318-proposal.pdf";a.click();URL.revokeObjectURL(url);}catch(err){alert(err.message);}});content.querySelectorAll("[data-question]").forEach(b=>b.onclick=()=>{view="messages";render();document.getElementById("portalMessage").focus();});const form=document.getElementById("portalMessageForm");if(form)form.onsubmit=async e=>{e.preventDefault();const field=document.getElementById("portalMessage"),status=document.getElementById("portalMessageStatus");status.textContent="Sending…";try{await respond(null,"question",field.value.trim());}catch(err){status.textContent=err.message;}};const upload=document.getElementById("portalDocumentForm");if(upload)upload.onsubmit=async e=>{e.preventDefault();const file=document.getElementById("portalDocumentFile").files[0],status=document.getElementById("portalDocumentStatus");if(!file||file.size>4194304){status.textContent="Choose a file smaller than 4 MB.";return;}status.textContent="Uploading…";const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]);reader.onerror=reject;reader.readAsDataURL(file);});try{const response=await fetch("/api/portal-document",{method:"POST",headers:{"Content-Type":"application/json","X-Portal-Token":token},body:JSON.stringify({fileName:file.name,mimeType:file.type,data:encoded})});if(!response.ok)throw new Error((await response.json()).error);data=await snapshot();render();}catch(err){status.textContent=err.message;}};}
  function showError(err){loading.hidden=true;app.hidden=true;errorBox.hidden=false;document.getElementById("portalErrorText").textContent=err?.message||"Ask 318 Food Co. for a fresh portal link.";}
  document.querySelectorAll("[data-portal-view]").forEach(b=>b.onclick=()=>{view=b.dataset.portalView;render();});
  if(!token){showError(new Error("This portal link is incomplete."));return;}
  snapshot().then(result=>{data=result;loading.hidden=true;app.hidden=false;document.getElementById("portalGreeting").textContent=`Welcome, ${data.customer.company||data.customer.first_name||"there"}`;render();}).catch(showError);
})();
